# Generated by Django 5.1.1 on 2024-09-26 04:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KmParaAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoMantenimientoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('matrícula', models.CharField(max_length=50)),
                ('número_de_chasis', models.CharField(max_length=50)),
                ('capacidad_de_carga', models.CharField(max_length=50)),
                ('uso_del_vehiculo', models.CharField(max_length=50)),
                ('km_recorridos', models.BigIntegerField()),
                ('intervalo_mantenimiento', models.IntegerField()),
                ('intervalo_cambio_filtro_aceite', models.IntegerField()),
                ('intervalo_cambio_filtro_aire_combustible', models.IntegerField()),
                ('intervalo_cambio_aceite_caja_corona', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='vehiculo/image')),
                ('fecha_ultimo_mantenimiento', models.DateField(default=datetime.date.today)),
                ('nombre_chofer', models.CharField(max_length=50)),
                ('teléfono_chofer', models.CharField(max_length=10)),
                ('dirección_chofer', models.CharField(max_length=30)),
                ('dni_chofer', models.BigIntegerField(blank=True, default=0, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MantenimientoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(default=datetime.date.today)),
                ('hora_inicio', models.TimeField(default=datetime.time(4, 40, 13, 654964))),
                ('fecha_fin', models.DateField(default=datetime.date.today)),
                ('hora_fin', models.TimeField(default=datetime.time(4, 40, 13, 655017))),
                ('km_recorridos', models.BigIntegerField()),
                ('operador', models.CharField(max_length=100)),
                ('descripción', models.TextField(max_length=400)),
                ('partes_y_piezas', models.TextField(max_length=400)),
                ('imagen', models.ImageField(default=None, upload_to='vehiculo/mantenimiento/imagen')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mUP_vehiculo.tipomantenimientovehiculo')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mUP_vehiculo.vehiculo')),
            ],
        ),
    ]
