# Generated by Django 5.1.1 on 2024-11-29 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mUP_vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimientovehiculo',
            name='hora_fin',
            field=models.TimeField(default=datetime.time(16, 48, 43, 335877)),
        ),
        migrations.AlterField(
            model_name='mantenimientovehiculo',
            name='hora_inicio',
            field=models.TimeField(default=datetime.time(16, 48, 43, 335832)),
        ),
        migrations.AddIndex(
            model_name='kmparaalerta',
            index=models.Index(fields=['km'], name='mUP_vehicul_km_71d820_idx'),
        ),
        migrations.AddIndex(
            model_name='mantenimientovehiculo',
            index=models.Index(fields=['vehiculo'], name='mUP_vehicul_vehicul_838f7b_idx'),
        ),
        migrations.AddIndex(
            model_name='tipomantenimientovehiculo',
            index=models.Index(fields=['tipo'], name='mUP_vehicul_tipo_3e0282_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiculo',
            index=models.Index(fields=['marca'], name='mUP_vehicul_marca_10d022_idx'),
        ),
    ]
