# Generated by Django 5.1.1 on 2024-11-29 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mUP_repuesto', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inventario',
            index=models.Index(fields=['parte'], name='mUP_repuest_parte_i_34a495_idx'),
        ),
        migrations.AddIndex(
            model_name='maquina',
            index=models.Index(fields=['nombre'], name='mUP_repuest_nombre_941c69_idx'),
        ),
        migrations.AddIndex(
            model_name='parte',
            index=models.Index(fields=['nombre'], name='mUP_repuest_nombre_902aef_idx'),
        ),
        migrations.AddIndex(
            model_name='parte',
            index=models.Index(fields=['maquina'], name='mUP_repuest_maquina_656805_idx'),
        ),
    ]
