# Generated by Django 5.1.1 on 2024-11-29 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mUP_herramienta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimientoherramienta',
            name='hora',
            field=models.TimeField(default=datetime.time(16, 48, 43, 322511)),
        ),
        migrations.AddIndex(
            model_name='herramienta',
            index=models.Index(fields=['nombre'], name='mUP_herrami_nombre_86ee61_idx'),
        ),
        migrations.AddIndex(
            model_name='mantenimientoherramienta',
            index=models.Index(fields=['herramienta'], name='mUP_herrami_herrami_c456c5_idx'),
        ),
        migrations.AddIndex(
            model_name='tipomantenimientoherramienta',
            index=models.Index(fields=['tipo'], name='mUP_herrami_tipo_735eb5_idx'),
        ),
    ]
