# Generated by Django 5.1.1 on 2024-09-23 17:50

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tamaño', models.CharField(max_length=100)),
                ('encargado', models.CharField(max_length=100)),
                ('teléfono_encargado', models.CharField(max_length=100)),
                ('descripción', models.TextField(max_length=500)),
                ('ubicación', models.CharField(max_length=100)),
                ('capacidad', models.CharField(max_length=100)),
                ('tipo_de_área', models.CharField(max_length=100)),
                ('estado_de_ocupación', models.CharField(max_length=100)),
                ('fecha_ultimo_mantenimiento', models.DateField(default=datetime.date.today)),
                ('intervalo_mantenimiento', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='area/imagen')),
            ],
        ),
        migrations.CreateModel(
            name='DiasParaAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('días', models.IntegerField(default=7)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMantenimientoArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MantenimientoArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(default=datetime.date.today)),
                ('hora_inicio', models.TimeField(default=datetime.time(17, 50, 31, 968214))),
                ('fecha_fin', models.DateField(default=datetime.date.today)),
                ('hora_fin', models.TimeField(default=datetime.time(17, 50, 31, 968290))),
                ('operador', models.CharField(default='', max_length=100)),
                ('descripción', models.TextField(default='', max_length=500)),
                ('imagen_antes', models.ImageField(default=None, upload_to='area/mantenimiento/antes')),
                ('imagen_después', models.ImageField(default=None, upload_to='area/mantenimiento/después')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mUP_area.area')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mUP_area.tipomantenimientoarea')),
            ],
        ),
    ]
