# Generated by Django 5.1.1 on 2024-11-29 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mUP_area', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimientoarea',
            name='hora_fin',
            field=models.TimeField(default=datetime.time(16, 48, 43, 315592)),
        ),
        migrations.AlterField(
            model_name='mantenimientoarea',
            name='hora_inicio',
            field=models.TimeField(default=datetime.time(16, 48, 43, 315536)),
        ),
        migrations.AddIndex(
            model_name='area',
            index=models.Index(fields=['nombre'], name='mUP_area_ar_nombre_c58089_idx'),
        ),
        migrations.AddIndex(
            model_name='diasparaalerta',
            index=models.Index(fields=['días'], name='mUP_area_di_días_151450_idx'),
        ),
        migrations.AddIndex(
            model_name='mantenimientoarea',
            index=models.Index(fields=['area'], name='mUP_area_ma_area_id_8c8b40_idx'),
        ),
        migrations.AddIndex(
            model_name='tipomantenimientoarea',
            index=models.Index(fields=['tipo'], name='mUP_area_ti_tipo_ffb5a0_idx'),
        ),
    ]
