# Generated by Django 5.1.1 on 2024-09-16 21:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mUP_area', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiasParaAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('días', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='mantenimientoarea',
            name='hora_fin',
            field=models.TimeField(default=datetime.time(21, 40, 10, 348582)),
        ),
        migrations.AlterField(
            model_name='mantenimientoarea',
            name='hora_inicio',
            field=models.TimeField(default=datetime.time(21, 40, 10, 348520)),
        ),
    ]
