# Generated by Django 5.1.1 on 2024-09-23 17:51

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HorasParaAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas', models.IntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('encargado', models.CharField(max_length=100)),
                ('teléfono_encargado', models.CharField(max_length=100)),
                ('descripción', models.TextField(max_length=500)),
                ('ubicación', models.CharField(max_length=100)),
                ('tipo_de_máquina', models.CharField(max_length=100)),
                ('número_de_serie_o_modelo', models.CharField(max_length=100)),
                ('proveedor', models.CharField(max_length=100)),
                ('costo_de_adquisición', models.IntegerField()),
                ('fecha_de_adquisición', models.DateField(default=datetime.date.today)),
                ('fecha_de_instalación', models.DateField(default=datetime.date.today)),
                ('estado_de_garantía', models.CharField(max_length=100)),
                ('consumo_de_energía', models.CharField(max_length=100)),
                ('horas_máquina_trabajada', models.IntegerField(default=0)),
                ('intervalo_mantenimiento', models.IntegerField()),
                ('fecha_ultimo_mantenimiento', models.DateField(default=datetime.date.today)),
                ('imagen', models.ImageField(upload_to='maquina/imagen')),
            ],
        ),
        migrations.CreateModel(
            name='TipoMantenimientoMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MantenimientoMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(default=datetime.date.today)),
                ('hora_inicio', models.TimeField(default=datetime.time(17, 51, 3, 991466))),
                ('fecha_fin', models.DateField(default=datetime.date.today)),
                ('hora_fin', models.TimeField(default=datetime.time(17, 51, 3, 991508))),
                ('operador', models.CharField(default='', max_length=100)),
                ('hr_maquina', models.IntegerField(default=0)),
                ('partes_y_piezas', models.TextField(default='', max_length=500)),
                ('descripción', models.TextField(default='', max_length=500)),
                ('imagen', models.ImageField(default=None, upload_to='maquina/mantenimiento/image')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mUP_maquina.maquina')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mUP_maquina.tipomantenimientomaquina')),
            ],
        ),
    ]
