# Generated by Django 5.1.1 on 2024-09-24 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mUP_maquina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimientomaquina',
            name='hora_fin',
            field=models.TimeField(default=datetime.time(16, 4, 28, 456282)),
        ),
        migrations.AlterField(
            model_name='mantenimientomaquina',
            name='hora_inicio',
            field=models.TimeField(default=datetime.time(16, 4, 28, 456228)),
        ),
        migrations.AlterField(
            model_name='mantenimientomaquina',
            name='imagen',
            field=models.ImageField(default=None, upload_to='maquina/mantenimiento/imagen'),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='horas_máquina_trabajada',
            field=models.IntegerField(),
        ),
    ]
