# Generated by Django 5.1.1 on 2024-11-29 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mUP_maquina', '0002_alter_mantenimientomaquina_hora_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimientomaquina',
            name='hora_fin',
            field=models.TimeField(default=datetime.time(16, 48, 43, 326565)),
        ),
        migrations.AlterField(
            model_name='mantenimientomaquina',
            name='hora_inicio',
            field=models.TimeField(default=datetime.time(16, 48, 43, 326522)),
        ),
        migrations.AddIndex(
            model_name='horasparaalerta',
            index=models.Index(fields=['horas'], name='mUP_maquina_horas_940cac_idx'),
        ),
        migrations.AddIndex(
            model_name='mantenimientomaquina',
            index=models.Index(fields=['maquina'], name='mUP_maquina_maquina_fd3f2c_idx'),
        ),
        migrations.AddIndex(
            model_name='maquina',
            index=models.Index(fields=['nombre'], name='mUP_maquina_nombre_8a9dcf_idx'),
        ),
        migrations.AddIndex(
            model_name='tipomantenimientomaquina',
            index=models.Index(fields=['tipo'], name='mUP_maquina_tipo_e245d6_idx'),
        ),
    ]
