# Generated by Django 5.1.1 on 2024-09-20 13:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiasParaAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('días', models.IntegerField(default=7)),
            ],
        ),
        migrations.CreateModel(
            name='PC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('número_de_inventario', models.CharField(max_length=100)),
                ('encargado', models.CharField(max_length=100)),
                ('teléfono_encargado', models.CharField(max_length=100)),
                ('descripción', models.TextField(max_length=500)),
                ('ubicación', models.CharField(max_length=100)),
                ('costo_de_adquisición', models.IntegerField()),
                ('fecha_de_adquisición', models.DateField(default=datetime.date.today)),
                ('fecha_de_retirada', models.DateField(default=datetime.date.today)),
                ('estado', models.CharField(max_length=100)),
                ('garantía', models.CharField(max_length=100)),
                ('software_instalado', models.CharField(max_length=100)),
                ('fecha_ultimo_mantenimiento', models.DateField(default=datetime.date.today)),
                ('intervalo_mantenimiento', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='pc/imagen')),
            ],
        ),
        migrations.CreateModel(
            name='TipoMantenimientoPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MantenimientoPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(default=datetime.date.today)),
                ('hora_inicio', models.TimeField(default=datetime.time(13, 40, 32, 679400))),
                ('fecha_fin', models.DateField(default=datetime.date.today)),
                ('hora_fin', models.TimeField(default=datetime.time(13, 40, 32, 679445))),
                ('operador', models.CharField(default='', max_length=100)),
                ('partes_y_piezas', models.TextField(default='', max_length=500)),
                ('descripción', models.TextField(default='', max_length=500)),
                ('imagen', models.ImageField(default=None, upload_to='pc/mantenimiento/imagen')),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mUP_pc.pc')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mUP_pc.tipomantenimientopc')),
            ],
        ),
    ]
