# Generated by Django 5.1.1 on 2024-11-29 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mUP_pc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimientopc',
            name='hora_fin',
            field=models.TimeField(default=datetime.time(16, 48, 43, 331147)),
        ),
        migrations.AlterField(
            model_name='mantenimientopc',
            name='hora_inicio',
            field=models.TimeField(default=datetime.time(16, 48, 43, 331106)),
        ),
        migrations.AddIndex(
            model_name='diasparaalerta',
            index=models.Index(fields=['días'], name='mUP_pc_dias_días_087d3d_idx'),
        ),
        migrations.AddIndex(
            model_name='mantenimientopc',
            index=models.Index(fields=['pc'], name='mUP_pc_mant_pc_id_7b8536_idx'),
        ),
        migrations.AddIndex(
            model_name='pc',
            index=models.Index(fields=['nombre'], name='mUP_pc_pc_nombre_9f9d36_idx'),
        ),
        migrations.AddIndex(
            model_name='tipomantenimientopc',
            index=models.Index(fields=['tipo'], name='mUP_pc_tipo_tipo_482621_idx'),
        ),
    ]
